### ISSUE TITLE
Generated XML lacks boilerplate

### ISSUE THREAD

**Issue by c-alpha** [dalanicolai/sketch-mode#4]
Hello, @dalanicolai. **First of all, many thanks for starting `sketch-mode`!** It looks awesome, and very promising. I can't wait to try out the `org-babel` integration... 😉 

You can always check the XML you produce at https://validator.w3.org/check. It is SVG-aware, but misses out on quite a couple of issues. Its main use is for HTML, where it excels. Using vector drawing apps to get the XML right is not a strategy I can recommend either. They all implement various "interpretations" of the standard.

I use XML in my daily work a lot, and I'm happy to throw any test materials you might have at my XML workbench and pass the test results back to you.

At the very basic level, you're missing the XML processing instruction, and the `DOCTYPE` element:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%">
    <!-- your content here... -->
</svg>
```
Without these two elements, it will never be a valid DTD instance document. By referencing the DTD, the version is also fixed (i.e. `@version` on the `svg` element is redundant).

**Comment by dalanicolai** [comment]
Thank you for your great feedback and suggestions. Indeed, I am only a hobbyist programmer, and I had no knowledge about XML, so it is nice to get notified and learn about these things. I am actually simply using the `svg.el` library. So also, I think that, in case this should get fixed, it should be done in the `svg.el` library (but I guess it should then be added as an option/argument to `svg-create`).

 So I have read the major part of the XML tutorial on w3schools.com now, which was a useful thing to do. I have also learned what is the purpose of the DTD, and it could be useful for 'high demanding' users.

On the other hand, I have also really quickly checked out some svg tutorials (It might be wise for me to take a closer look at those, but until now I don't know much about svg either). Anyway, I have found a comment [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Getting_Started) which recommends to leave out the doctype declaration (see the first point under the svg image). So, I assume it is not of major importance (especially because this package is meant only for simple svg's). However, it would still be nice to implement it via an optional argument in `svg-create` (and sketch-mode). Let me know if you think I am making a wrong assumption.

Anyway, thanks for the positive reaction and thinking with me, it is much appreciated.

**Comment by c-alpha** [comment]
Well, there are two use-cases we need to distinguish. The first one is a stand-alone SVG file, which you can open and edit in a vector drawing app, such as e.g. inkscape, and which is what I was referring to. The second one is an SVG image inlined in a HTML5 document, which is what the Mozilla page you're referencing describes.

In the second case, the definition of the SVG elements is included by the definition of HTML5. I.e. by understanding HTML5, the browser implicitly also "speaks" SVG. And both, the web server and the browser have out-of-band means to infer that the content is SVG, e.g. by inspecting the `Content-Type` http header (browser), or by information about the  `.svg` file name extension in a configuration file (server). Thus, if you have an SVG file without the boilerplate, and include it in an HTML page, or open it "manually" in a web browser, it will work and the browser will render it. This is because the browser and server have additional information from the context about what to do with the data.

Things may play out differently though, when you try to open such a file in a vector drawing app, which supports multiple file formats, as they typically do. In this scenario the app has no supplementary information about the file being opened. Depending on whether the app's developers have incorporated some heuristics, or not, the app may open the file, or complain about a broken image file. To be on the safe side, the boilerplate should hence always be included in stand-alone SVG files. Web browsers will not be disturbed by files being included via `<object>` or `<img>` elements, and which contain the boilerplate, and render them correctly. Being able to unambiguously recognise the content type from the resource file itself finally becomes paramount in the context of content creation systems such as e.g. [DITA](https://en.wikipedia.org/wiki/Darwin_Information_Typing_Architecture) and [DITA-OT](https://www.dita-ot.org).

Whether `svg.el` should be amended to produce the boilerplate preamble. or not, is up for discussion, I think. What is the users' expectation wrt. `svg.el`? Well, that it creates SVG images. What will the user do with that image (cf. the two use-cases described above)? `svg.el` can't know what the user's intentions are, I guess. In that light, and IMHO, my expectation would be that the code that uses `svg.el` (i.e. `sketch-mode.el`) adds the boilerplate preamble if and when saving to a file. Just my two cents anyway...

**Comment by dalanicolai** [comment]
Thank you for this explanation. It sounds like it might be handy to add this then... so I did.
